[emz]
defeat = 61
victory = 54
draw = 1

[total]
defeat = 2
victory = 3
draw = 0

[shelly]
defeat = 0
victory = 0
draw = 0

[colt]
defeat = 0
victory = 2
draw = 0

[brock]
defeat = 4
victory = 19
draw = 1

[nita]
defeat = 2
victory = 3
draw = 0
